image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - ./gradlew assemble -Pomdb_api_key="$omdb_api_key"

test:
  stage: test
  script:
    - ./gradlew check -Pomdb_api_key="$omdb_api_key"